### ISSUE TITLE
Build of read the docs fails

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf-schema-language#5]
The build of the hdmf schema language docs on RTD currently fails with

```
Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/hdmf-schema-language/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hdmf-schema-language/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hdmf-schema-language/checkouts/latest/source/conf.py", line 16, in <module>
    from ruamel import yaml
ModuleNotFoundError: No module named 'ruamel'
```

**Comment by rly** [comment]
Resolved with https://github.com/hdmf-dev/hdmf-schema-language/commit/35cc7fe5e564996c79c08b52b42e74b8f6a87987 and changes to the RTD config.
